In [1]:
import pandas as pd

In [8]:
import env

In [5]:
import os

In [2]:
import acquire

In [3]:
from acquire import get_telco_data

In [10]:
def get_connection(db, user=env.user, host=env.host, password=env.password):
    return f'mysql+pymysql://{user}:{password}@{host}/{db}'

In [12]:
get_telco_data()

,Unnamed: 0,payment_type_id,internet_service_type_id,contract_type_id,customer_id,gender,senior_citizen,partner,dependents,tenure,...,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,churn,contract_type,internet_service_type,payment_type
0,0,2,1,1,0003-MKNFE,Male,0,No,No,9,...,No,No,Yes,No,59.90,542.4,No,Month-to-month,DSL,Mailed check
1,1,4,1,1,0013-MHZWF,Female,0,No,Yes,9,...,Yes,Yes,Yes,Yes,69.40,571.45,No,Month-to-month,DSL,Credit card (automatic)
2,2,1,1,1,0015-UOCOJ,Female,1,No,No,7,...,No,No,No,Yes,48.20,340.35,No,Month-to-month,DSL,Electronic check
3,3,1,1,1,0023-HGHWL,Male,1,No,No,1,...,No,No,No,Yes,25.10,25.1,Yes,Month-to-month,DSL,Electronic check
4,4,3,1,1,0032-PGELS,Female,0,Yes,Yes,1,...,No,No,No,No,30.50,30.5,Yes,Month-to-month,DSL,Bank transfer (automatic)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,7038,4,3,3,9950-MTGYX,Male,0,Yes,Yes,28,...,No internet service,No internet service,No internet service,Yes,20.30,487.95,No,Two year,None,Credit card (automatic)
7039,7039,2,3,3,9953-ZMKSM,Male,0,No,No,63,...,No internet service,No internet service,No internet service,No,25.25,1559.3,No,Two year,None,Mailed check
7040,7040,4,3,3,9964-WBQDJ,Female,0,Yes,No,71,...,No internet service,No internet service,No internet service,Yes,24.40,1725.4,No,Two year,None,Credit card (automatic)
7041,7041,3,3,3,9972-EWRJS,Female,0,Yes,Yes,67,...,No internet service,No internet service,No internet service,Yes,19.25,1372.9,No,Two year,None,Bank transfer (automatic)
7042,7042,4,3,3,9975-GPKZU,Male,0,Yes,Yes,46,...,No internet service,No internet service,No internet service,No,19.75,856.5,No,Two year,None,Credit card (automatic)